name: cifar10_stage2
print_freq: 40
workers: 8
log_dir: '/media/gaor2/Elements/saved_file/Calibration/MiSLAS/imb001/stage2_imb001/logs'
model_dir: '/media/gaor2/Elements/saved_file/Calibration/MiSLAS/imb001/stage2_imb001/ckps'
code_dir: '/media/gaor2/Elements/saved_file/Calibration/MiSLAS/imb001/stage2_imb001/code'
use_focal: False

# dataset & model setting
dataset: 'cifar10'
data_path: '/media/gaor2/Elements/data/cifar10'
num_classes: 10
imb_factor: 0.01

backbone: 'resnet32_fe'
largenet: False

resume: '/media/gaor2/Elements/saved_file/Calibration/MiSLAS/imb001/stage1_imb001/ckps/model_best.pth.tar'
head_class_idx:
  - 0
  - 3
med_class_idx:
  - 3
  - 7
tail_class_idx:
  - 7
  - 10



# Train
mode: 'stage2'
smooth_head: 0.1
smooth_tail: 0.0
shift_bn: False
lr_factor: 0.2
lr: 0.1
batch_size: 128
weight_decay: 5e-4
num_epochs: 100
momentum: 0.9
mixup: False
alpha: 1.0




